/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcmeRouteImport } from './routes/acme'
import { Route as AgnesBernauerRouteImport } from './routes/agnes-bernauer'
import { Route as BonusContentRouteImport } from './routes/bonus-content'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as FreecellRouteImport } from './routes/freecell'
import { Route as GolfRouteImport } from './routes/golf'
import { Route as GrandfathersClockRouteImport } from './routes/grandfathers-clock'
import { Route as KlondikeDraw1RouteImport } from './routes/klondike-draw-1'
import { Route as KlondikeDraw3RouteImport } from './routes/klondike-draw-3'
import { Route as NewGameRouteImport } from './routes/new-game'
import { Route as PyramidRouteImport } from './routes/pyramid'
import { Route as PyramidAltRouteImport } from './routes/pyramid-alt'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimpleSimonRouteImport } from './routes/simple-simon'
import { Route as TriPeaksRouteImport } from './routes/tri-peaks'
import { Route as TriPeaksAltRouteImport } from './routes/tri-peaks-alt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcmeRoute = AcmeRouteImport.update({
  id: '/acme',
  path: '/acme',
  getParentRoute: () => rootRouteImport,
} as any)
const AgnesBernauerRoute = AgnesBernauerRouteImport.update({
  id: '/agnes-bernauer',
  path: '/agnes-bernauer',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusContentRoute = BonusContentRouteImport.update({
  id: '/bonus-content',
  path: '/bonus-content',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const FreecellRoute = FreecellRouteImport.update({
  id: '/freecell',
  path: '/freecell',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfRoute = GolfRouteImport.update({
  id: '/golf',
  path: '/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const GrandfathersClockRoute = GrandfathersClockRouteImport.update({
  id: '/grandfathers-clock',
  path: '/grandfathers-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const KlondikeDraw1Route = KlondikeDraw1RouteImport.update({
  id: '/klondike-draw-1',
  path: '/klondike-draw-1',
  getParentRoute: () => rootRouteImport,
} as any)
const KlondikeDraw3Route = KlondikeDraw3RouteImport.update({
  id: '/klondike-draw-3',
  path: '/klondike-draw-3',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGameRoute = NewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRouteImport,
} as any)
const PyramidRoute = PyramidRouteImport.update({
  id: '/pyramid',
  path: '/pyramid',
  getParentRoute: () => rootRouteImport,
} as any)
const PyramidAltRoute = PyramidAltRouteImport.update({
  id: '/pyramid-alt',
  path: '/pyramid-alt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleSimonRoute = SimpleSimonRouteImport.update({
  id: '/simple-simon',
  path: '/simple-simon',
  getParentRoute: () => rootRouteImport,
} as any)
const TriPeaksRoute = TriPeaksRouteImport.update({
  id: '/tri-peaks',
  path: '/tri-peaks',
  getParentRoute: () => rootRouteImport,
} as any)
const TriPeaksAltRoute = TriPeaksAltRouteImport.update({
  id: '/tri-peaks-alt',
  path: '/tri-peaks-alt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acme': typeof AcmeRoute
  '/agnes-bernauer': typeof AgnesBernauerRoute
  '/bonus-content': typeof BonusContentRoute
  '/credits': typeof CreditsRoute
  '/freecell': typeof FreecellRoute
  '/golf': typeof GolfRoute
  '/grandfathers-clock': typeof GrandfathersClockRoute
  '/klondike-draw-1': typeof KlondikeDraw1Route
  '/klondike-draw-3': typeof KlondikeDraw3Route
  '/new-game': typeof NewGameRoute
  '/pyramid': typeof PyramidRoute
  '/pyramid-alt': typeof PyramidAltRoute
  '/settings': typeof SettingsRoute
  '/simple-simon': typeof SimpleSimonRoute
  '/tri-peaks': typeof TriPeaksRoute
  '/tri-peaks-alt': typeof TriPeaksAltRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acme': typeof AcmeRoute
  '/agnes-bernauer': typeof AgnesBernauerRoute
  '/bonus-content': typeof BonusContentRoute
  '/credits': typeof CreditsRoute
  '/freecell': typeof FreecellRoute
  '/golf': typeof GolfRoute
  '/grandfathers-clock': typeof GrandfathersClockRoute
  '/klondike-draw-1': typeof KlondikeDraw1Route
  '/klondike-draw-3': typeof KlondikeDraw3Route
  '/new-game': typeof NewGameRoute
  '/pyramid': typeof PyramidRoute
  '/pyramid-alt': typeof PyramidAltRoute
  '/settings': typeof SettingsRoute
  '/simple-simon': typeof SimpleSimonRoute
  '/tri-peaks': typeof TriPeaksRoute
  '/tri-peaks-alt': typeof TriPeaksAltRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acme': typeof AcmeRoute
  '/agnes-bernauer': typeof AgnesBernauerRoute
  '/bonus-content': typeof BonusContentRoute
  '/credits': typeof CreditsRoute
  '/freecell': typeof FreecellRoute
  '/golf': typeof GolfRoute
  '/grandfathers-clock': typeof GrandfathersClockRoute
  '/klondike-draw-1': typeof KlondikeDraw1Route
  '/klondike-draw-3': typeof KlondikeDraw3Route
  '/new-game': typeof NewGameRoute
  '/pyramid': typeof PyramidRoute
  '/pyramid-alt': typeof PyramidAltRoute
  '/settings': typeof SettingsRoute
  '/simple-simon': typeof SimpleSimonRoute
  '/tri-peaks': typeof TriPeaksRoute
  '/tri-peaks-alt': typeof TriPeaksAltRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acme'
    | '/agnes-bernauer'
    | '/bonus-content'
    | '/credits'
    | '/freecell'
    | '/golf'
    | '/grandfathers-clock'
    | '/klondike-draw-1'
    | '/klondike-draw-3'
    | '/new-game'
    | '/pyramid'
    | '/pyramid-alt'
    | '/settings'
    | '/simple-simon'
    | '/tri-peaks'
    | '/tri-peaks-alt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acme'
    | '/agnes-bernauer'
    | '/bonus-content'
    | '/credits'
    | '/freecell'
    | '/golf'
    | '/grandfathers-clock'
    | '/klondike-draw-1'
    | '/klondike-draw-3'
    | '/new-game'
    | '/pyramid'
    | '/pyramid-alt'
    | '/settings'
    | '/simple-simon'
    | '/tri-peaks'
    | '/tri-peaks-alt'
  id:
    | '__root__'
    | '/'
    | '/acme'
    | '/agnes-bernauer'
    | '/bonus-content'
    | '/credits'
    | '/freecell'
    | '/golf'
    | '/grandfathers-clock'
    | '/klondike-draw-1'
    | '/klondike-draw-3'
    | '/new-game'
    | '/pyramid'
    | '/pyramid-alt'
    | '/settings'
    | '/simple-simon'
    | '/tri-peaks'
    | '/tri-peaks-alt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcmeRoute: typeof AcmeRoute
  AgnesBernauerRoute: typeof AgnesBernauerRoute
  BonusContentRoute: typeof BonusContentRoute
  CreditsRoute: typeof CreditsRoute
  FreecellRoute: typeof FreecellRoute
  GolfRoute: typeof GolfRoute
  GrandfathersClockRoute: typeof GrandfathersClockRoute
  KlondikeDraw1Route: typeof KlondikeDraw1Route
  KlondikeDraw3Route: typeof KlondikeDraw3Route
  NewGameRoute: typeof NewGameRoute
  PyramidRoute: typeof PyramidRoute
  PyramidAltRoute: typeof PyramidAltRoute
  SettingsRoute: typeof SettingsRoute
  SimpleSimonRoute: typeof SimpleSimonRoute
  TriPeaksRoute: typeof TriPeaksRoute
  TriPeaksAltRoute: typeof TriPeaksAltRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acme': {
      id: '/acme'
      path: '/acme'
      fullPath: '/acme'
      preLoaderRoute: typeof AcmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agnes-bernauer': {
      id: '/agnes-bernauer'
      path: '/agnes-bernauer'
      fullPath: '/agnes-bernauer'
      preLoaderRoute: typeof AgnesBernauerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-content': {
      id: '/bonus-content'
      path: '/bonus-content'
      fullPath: '/bonus-content'
      preLoaderRoute: typeof BonusContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freecell': {
      id: '/freecell'
      path: '/freecell'
      fullPath: '/freecell'
      preLoaderRoute: typeof FreecellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf': {
      id: '/golf'
      path: '/golf'
      fullPath: '/golf'
      preLoaderRoute: typeof GolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grandfathers-clock': {
      id: '/grandfathers-clock'
      path: '/grandfathers-clock'
      fullPath: '/grandfathers-clock'
      preLoaderRoute: typeof GrandfathersClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klondike-draw-1': {
      id: '/klondike-draw-1'
      path: '/klondike-draw-1'
      fullPath: '/klondike-draw-1'
      preLoaderRoute: typeof KlondikeDraw1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klondike-draw-3': {
      id: '/klondike-draw-3'
      path: '/klondike-draw-3'
      fullPath: '/klondike-draw-3'
      preLoaderRoute: typeof KlondikeDraw3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyramid': {
      id: '/pyramid'
      path: '/pyramid'
      fullPath: '/pyramid'
      preLoaderRoute: typeof PyramidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyramid-alt': {
      id: '/pyramid-alt'
      path: '/pyramid-alt'
      fullPath: '/pyramid-alt'
      preLoaderRoute: typeof PyramidAltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-simon': {
      id: '/simple-simon'
      path: '/simple-simon'
      fullPath: '/simple-simon'
      preLoaderRoute: typeof SimpleSimonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri-peaks': {
      id: '/tri-peaks'
      path: '/tri-peaks'
      fullPath: '/tri-peaks'
      preLoaderRoute: typeof TriPeaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri-peaks-alt': {
      id: '/tri-peaks-alt'
      path: '/tri-peaks-alt'
      fullPath: '/tri-peaks-alt'
      preLoaderRoute: typeof TriPeaksAltRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcmeRoute: AcmeRoute,
  AgnesBernauerRoute: AgnesBernauerRoute,
  BonusContentRoute: BonusContentRoute,
  CreditsRoute: CreditsRoute,
  FreecellRoute: FreecellRoute,
  GolfRoute: GolfRoute,
  GrandfathersClockRoute: GrandfathersClockRoute,
  KlondikeDraw1Route: KlondikeDraw1Route,
  KlondikeDraw3Route: KlondikeDraw3Route,
  NewGameRoute: NewGameRoute,
  PyramidRoute: PyramidRoute,
  PyramidAltRoute: PyramidAltRoute,
  SettingsRoute: SettingsRoute,
  SimpleSimonRoute: SimpleSimonRoute,
  TriPeaksRoute: TriPeaksRoute,
  TriPeaksAltRoute: TriPeaksAltRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
